- name: variables
  hosts: local
  vars: # Play level variables, global variables
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: SIVAKUMAR
  tasks:
    - name: print the variables
      vars:
        COURSE: Ansible # task level variables
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

    - name: print the variables1
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

    
