- name: variables 
  hosts: local
  connection: local
  vars:
    GREET="PLAY"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREET
    prompt: Enter the value
    private: false
  tasks:
  - name: print the variable
    vars:
      GREET="PLAY"
    ansible.builtin.debug:
     msg: "Hello From {{ GREET }}"