- name: check value greater than 10 or not
  hosts: local
  connection: local
  vars_prompt:
    - name: my_value
      prompt: Enter the value
      private: false
  tasks:
  - name: print if number greater than 10
    ansible.builtin.debug:
     msg: "Given number {{ my_value }} is greater than 10"
    when: my_value > 10
  
  - name: print if number is less than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{ my_value }} is less than or equal to 10"
    when: my_value <= 10