- name: loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: installed    
    loop:
    - { name: 'git', state: 'present'}
    - { name: 'mysql', state: 'absent'}
    - { name: 'git', state: 'present'}
    - { name: 'zip', state: 'absent'}
    # - gcc
    # - mysql
    # - git
    # - zip