- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: execute ls command
    ansible.builtin.command: ls
  # - name: execute ls command and redirect the output
  #   ansible.builtin.command: ls -ltr > /tmp/output.txt
  - name: execute ls command and redirect the output in shell module
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
  - name: run the command take the register the output in a varaiable
    ansible.builtin.command: ls -ltr
    register: command_result
  
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"
    